version: '3.9'
services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  web:
    image: odoo12
    restart: always
    depends_on:
      - db
      - mq
      - redis
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
  celery:
    image: odoo12
    restart: always
    depends_on:
      - db
      - mq
      - redis
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ['celery', '--loglevel=INFO']
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/passwd_pg
      - PGDATA=/var/lib/postgresql/data/pgdata
    secrets:
      - passwd_pg
    volumes:
      - ./data_db:/var/lib/postgresql/data
  mq:
    image: rabbitmq:3.8-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/passwd_rabbitmq
    secrets:
      - passwd_rabbitmq
    volumes:
      - ./data_mq:/var/lib/rabbitmq
  redis:
    image: redis
    restart: always
    volumes:
      - ./data_redis:/data
  minio:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"
    volumes:
      - ./data_minio:/data
    command:
      ['server', '/data', '--console-address', ':9001']

secrets:
  passwd_pg:
    file: ./secrets/passwd_pg
  passwd_rabbitmq:
    file: ./secrets/passwd_rabbitmq
