version: '3.9'
services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - web
      - chat
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  web:
    image: odoo12
    restart: always
    depends_on:
      - db
      - redis
      - mq
      - minio
    volumes:
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ['--max-cron-threads=0']
  chat:
    image: odoo12
    restart: always
    depends_on:
      - db
      - redis
      - mq
      - minio
    volumes:
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ['--', 'gevent']
  cron:
    image: odoo12
    restart: always
    depends_on:
      - db
      - redis
      - mq
      - minio
    volumes:
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ['--no-http']
  celery:
    image: odoo12
    restart: always
    depends_on:
      - db
      - redis
      - mq
      - minio
    volumes:
      - ./data_odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ['celery', '--loglevel=INFO']
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data_db:/var/lib/postgresql/data
  mq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15671:15671"
    volumes:
      - ./data_mq:/var/lib/rabbitmq
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data_redis:/data
    command: ['--requirepass', 'redis']
  minio:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS='odoo-files'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data_minio:/data
    command: ['server', '/data', '--console-address', ':9001']
